#######################################################################
### USER ##############################################################
#######################################################################

### ALL USERS REQUEST
GET http://localhost:3700/user/all

### CREATE A NEW USER
POST http://localhost:3700/user/new
Content-Type: application/json

{
    "username": "",
    "email": "elcrack8@gmail.com",
    "password": "12345679"
}

### FIND A USER FOR ID
GET http://localhost:3700/user/60859758743afc1c34c2005b

### UPDATE A USER FOR ID
PUT http://localhost:3700/user/update/60859ad0a9ec93272c6f11d8
Content-Type: application/json

{
    "roles": {
        "first": "Toplane",
        "second": "Adc"
      }
}

### DELETE A USER FOR ID
DELETE http://localhost:3700/user/delete/60854371ea479c1fb05d3c60

### GET TEAM BY USER REQUEST
GET http://localhost:3700/user/getTeam?username=ElNiggi

########################################################################
### TEAMS ##############################################################
########################################################################

### ALL TEAMS REQUEST
GET http://localhost:3700/team/all

### GET TOURNAMENT BY TEAM REQUEST
GET http://localhost:3700/team/getTournament?name=TEAM+REVEN

### CREATE A NEW TEAM
POST http://localhost:3700/team/new
Content-Type: application/json

{
    "name": "TEAM RAULLL"
}

### FIND A TEAM FOR ID
GET http://localhost:3700/team/608be39fea78be2c3c47e63b

### FIND NUMBER OF USERS IN A TEAM
GET http://localhost:3700/team/numberOfUsers/608be39fea78be2c3c47e63b


### UPDATE A TEAM FOR ID
PUT http://localhost:3700/team/update/6085aa24ccd0e21b58659c42
Content-Type: application/json

{
    "statistics": {
        "victories": 3,
        "defeats": 1,
        "rankingpoints": 2000
    }
}

### DELETE A TEAM FOR ID
DELETE http://localhost:3700/team/delete/608bfc3da57d3f26d480560f

### ASSIGN A USER FOR A TEAM
PUT http://localhost:3700/team/assignUser/608be39fea78be2c3c47e63b
Content-Type: application/json

{
    "user": "608be60abb89ac0d8012df93"
}

### REMOVE A USER FROM A TEAM
PUT http://localhost:3700/team/removeUser/608be39fea78be2c3c47e63b
Content-Type: application/json

{
    "user": "608be60abb89ac0d8012df93"
}

### ASSIGN ADMIN FOR A TEAM
PUT http://localhost:3700/team/assignAdmin/608be39fea78be2c3c47e63b
Content-Type: application/json

{
    "user": "608be60abb89ac0d8012df93"
}

########################################################################
### TOURNAMENTS ########################################################
########################################################################

### ALL TOURNAMENTS REQUEST
GET http://localhost:3700/tournament/all

### CREATE A NEW TOURNAMENT
POST http://localhost:3700/tournament/new
Content-Type: application/json

{
    "name": "The Best Manins",
    "size": 4
}

### FIND A TOURNAMENTS FOR ID
GET http://localhost:3700/tournament/608c0e519b4caf370417cfd5

### FIND NUMBER OF TEAMS IN A TOURNAMENT
GET http://localhost:3700/tournament/numberOfTeams/608c0e519b4caf370417cfd5

### UPDATE A TOURNAMENTS FOR ID
PUT http://localhost:3700/tournament/update/6085afe4fb473d6f4024ea71
Content-Type: application/json

{
    "size": 16
}

### DELETE A TOURNAMENTS FOR ID
DELETE http://localhost:3700/tournament/delete/6085afe4fb473d6f4024ea71

### ASSIGN A TEAM FOR A TOURNAMENT
PUT http://localhost:3700/tournament/assignTeam/608c0e519b4caf370417cfd5
Content-Type: application/json

{
    "team": "608be39fea78be2c3c47e63b"
}

### REMOVE A TEAM FROM A TOURNAMENT
PUT http://localhost:3700/tournament/removeTeam/608c0e519b4caf370417cfd5
Content-Type: application/json

{
    "team": "608be39fea78be2c3c47e63b"
}

### ASSIGN ADMIN FOR A TOURNAMENT
PUT http://localhost:3700/tournament/assignAdmin/608c0e519b4caf370417cfd5
Content-Type: application/json

{
    "user": "608be60abb89ac0d8012df93"
}