#######################################################################
### USER ##############################################################
#######################################################################

### ALL USERS REQUEST
GET http://localhost:3700/user/all

### CREATE A NEW USER
POST http://localhost:3700/user/new
Content-Type: application/json

{
    "username": "ElCrack",
    "email": "elcrack78@gmail.com",
    "password": "123456789"
}

### FIND A USER FOR ID
GET http://localhost:3700/user/60859758743afc1c34c2005b

### UPDATE A USER FOR ID
PUT http://localhost:3700/user/update/60859ad0a9ec93272c6f11d8
Content-Type: application/json

{
    "roles": {
        "first": "Toplane",
        "second": "Adc"
      }
}

### DELETE A USER FOR ID
DELETE http://localhost:3700/user/delete/60859758743afc1c34c2005b

########################################################################
### TEAMS ##############################################################
########################################################################

### ALL TEAMS REQUEST
GET http://localhost:3700/team/all

### CREATE A NEW TEAM
POST http://localhost:3700/team/new
Content-Type: application/json

{
    "name": "TEAM IBAI"
}

### FIND A TEAM FOR ID
GET http://localhost:3700/team/6085aa24ccd0e21b58659c42

### UPDATE A TEAM FOR ID
PUT http://localhost:3700/team/update/6085aa24ccd0e21b58659c42
Content-Type: application/json

{
    "statistics": {
        "victories": 3,
        "defeats": 1,
        "rankingpoints": 2000
    }
}

### DELETE A TEAM FOR ID
DELETE http://localhost:3700/team/delete/6085aa24ccd0e21b58659c42

########################################################################
### TOURNAMENTS ########################################################
########################################################################