#######################################################################
### USER ##############################################################
#######################################################################

### ALL USERS REQUEST
GET http://localhost:3700/user/all
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDk2YzU2Y2JlZjYyMjM0Zjg3NjVjNWMiLCJpYXQiOjE2MjA0OTM2NzYsImV4cCI6MTYyMDUzNjg3Nn0.a2kVN0m8yaKhmJ26EmR7i_UnC79I2KVIj8umcbreUTc
//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDk2Y2JkOGQxMDgyNDY4MjAzZDRmMTgiLCJpYXQiOjE2MjA0OTUzMjAsImV4cCI6MTYyMDUzODUyMH0.Qyn_mT2hLbR_Z6bL6TekbQnHLR85JRaiH6uOVRSK9Ug - OWO
### CREATE A NEW USER
POST http://localhost:3700/user/new
Content-Type: application/json

{
    "username": "OwO",
    "email": "owo@gmail.com",
    "password": "jojo"
}

### FIND A USER FOR ID
GET http://localhost:3700/user/60854371ea479c1fb05d3c60

### UPDATE A USER FOR ID
PUT http://localhost:3700/user/update/60859ad0a9ec93272c6f11d8
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDkwMGNlN2UzMDhmYzFmYjBkNWJmNzgiLCJpYXQiOjE2MjAwNjA3NzksImV4cCI6MTYyMDEwMzk3OX0.Hsd_NOTzu-eaEUkSfogcuBJWJ-grr5iBc8Oa_AwGpIQ

{
    "roles": {
        "first": "Toplane",
        "second": "Adc"
      }
}

### DELETE A USER FOR ID
DELETE http://localhost:3700/user/delete/6085a53ed802d9523cba9887
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDk2YzU2Y2JlZjYyMjM0Zjg3NjVjNWMiLCJpYXQiOjE2MjA0OTM2NzYsImV4cCI6MTYyMDUzNjg3Nn0.a2kVN0m8yaKhmJ26EmR7i_UnC79I2KVIj8umcbreUTc


### GET TEAM BY USER REQUEST
GET http://localhost:3700/user/getTeam?username=ElNiggi

########################################################################
### TEAMS ##############################################################
########################################################################

### ALL TEAMS REQUEST
GET http://localhost:3700/team/all

### GET TOURNAMENT BY TEAM REQUEST
GET http://localhost:3700/team/getTournament?name=TEAM+REVE

### CREATE A NEW TEAM
POST http://localhost:3700/team/new
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDk2YzU2Y2JlZjYyMjM0Zjg3NjVjNWMiLCJpYXQiOjE2MjA0OTM2NzYsImV4cCI6MTYyMDUzNjg3Nn0.a2kVN0m8yaKhmJ26EmR7i_UnC79I2KVIj8umcbreUTc

{
    "name": "TEAM RAULLL"
}

### FIND A TEAM FOR ID
GET http://localhost:3700/team/608be39fea78be2c3c47e63b

### FIND NUMBER OF USERS IN A TEAM
GET http://localhost:3700/team/numberOfUsers/608be39fea78be2c3c47e63b


### UPDATE A TEAM FOR ID
PUT http://localhost:3700/team/update/6085aa24ccd0e21b58659c42
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDkwMGNlN2UzMDhmYzFmYjBkNWJmNzgiLCJpYXQiOjE2MjAwNjA3NzksImV4cCI6MTYyMDEwMzk3OX0.Hsd_NOTzu-eaEUkSfogcuBJWJ-grr5iBc8Oa_AwGpIQ

{
    "statistics": {
        "victories": 3,
        "defeats": 1,
        "rankingpoints": 2000
    }
}

### DELETE A TEAM FOR ID
DELETE http://localhost:3700/team/delete/608bfc3da57d3f26d480560f

### ASSIGN A USER FOR A TEAM
PUT http://localhost:3700/team/assignUser/609036c170d03d16b89da151
Content-Type: application/json

{
    "user": "60900ce7e308fc1fb0d5bf78"
}

### REMOVE A USER FROM A TEAM
PUT http://localhost:3700/team/removeUser/609036c170d03d16b89da151
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDkwMGNlN2UzMDhmYzFmYjBkNWJmNzgiLCJpYXQiOjE2MjAwNjA3NzksImV4cCI6MTYyMDEwMzk3OX0.Hsd_NOTzu-eaEUkSfogcuBJWJ-grr5iBc8Oa_AwGpIQ

{
    "user": "60900ce7e308fc1fb0d5bf78"
}

########################################################################
### TOURNAMENTS ########################################################
########################################################################

### ALL TOURNAMENTS REQUEST
GET http://localhost:3700/tournament/all

### CREATE A NEW TOURNAMENT
POST http://localhost:3700/tournament/new
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDkwMGNlN2UzMDhmYzFmYjBkNWJmNzgiLCJpYXQiOjE2MjAwNjA3NzksImV4cCI6MTYyMDEwMzk3OX0.Hsd_NOTzu-eaEUkSfogcuBJWJ-grr5iBc8Oa_AwGpIQ

{
    "name": "The Best Manins",
    "size": 4
}

### FIND A TOURNAMENTS FOR ID
GET http://localhost:3700/tournament/608c0e519b4caf370417cfd5

### FIND NUMBER OF TEAMS IN A TOURNAMENT
GET http://localhost:3700/tournament/numberOfTeams/608c0e519b4caf370417cfd5

### UPDATE A TOURNAMENTS FOR ID
PUT http://localhost:3700/tournament/update/608c0e519b4caf370417cfd5
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDkwMGNlN2UzMDhmYzFmYjBkNWJmNzgiLCJpYXQiOjE2MjAwNjA3NzksImV4cCI6MTYyMDEwMzk3OX0.Hsd_NOTzu-eaEUkSfogcuBJWJ-grr5iBc8Oa_AwGpIQ

{
    "size": 8
}

### DELETE A TOURNAMENTS FOR ID
DELETE http://localhost:3700/tournament/delete/6085afe4fb473d6f4024ea71

### ASSIGN A TEAM FOR A TOURNAMENT
PUT http://localhost:3700/tournament/assignTeam/608c0e519b4caf370417cfd5
Content-Type: application/json

{
    "team": "608be39fea78be2c3c47e63b"
}

### REMOVE A TEAM FROM A TOURNAMENT
PUT http://localhost:3700/tournament/removeTeam/608c0e519b4caf370417cfd5
Content-Type: application/json

{
    "team": "608be39fea78be2c3c47e63b"
}

########################################################################
### LOGIN ##############################################################
########################################################################

### MATCH DEL USUARIO A LOGEAR
POST http://localhost:3700/login
Content-Type: application/json

{
    "email": "elcracks8@gmail.com",
    "password": "123456"
}

### RENOVAR TOKEN USUARIO
GET http://localhost:3700/login/renew
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDkwMGNlN2UzMDhmYzFmYjBkNWJmNzgiLCJpYXQiOjE2MjAwNjA3NzksImV4cCI6MTYyMDEwMzk3OX0.Hsd_NOTzu-eaEUkSfogcuBJWJ-grr5iBc8Oa_AwGpIQ


########################################################################
#### PETITION ##########################################################
########################################################################

### Peticion del usuario para entrar en un equipo
POST http://localhost:3700/petition/userToAdmin?teamId=6096cb0ed1082468203d4f17
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDk2Y2JkOGQxMDgyNDY4MjAzZDRmMTgiLCJpYXQiOjE2MjA0OTUzMjAsImV4cCI6MTYyMDUzODUyMH0.Qyn_mT2hLbR_Z6bL6TekbQnHLR85JRaiH6uOVRSK9Ug

